name: Lint and test the project
on:
  push:
    branches:
      - 'chore/120-cd'

jobs:
  lint_and_test:
    name: Static code analyze & Unit test
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.3.0

      - name: Print environments
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REST_API_ENDPOINT: ${{ secrets.REST_API_ENDPOINT }}
        run: |
          echo "${REST_API_ENDPOINT}"
